/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protobuf/bittorent.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protobuf/bittorent.pb-c.h"
void   node__init
                     (Node         *message)
{
  static const Node init_value = NODE__INIT;
  *message = init_value;
}
size_t node__get_packed_size
                     (const Node *message)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node__pack
                     (const Node *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node__pack_to_buffer
                     (const Node *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Node *
       node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Node *)
     protobuf_c_message_unpack (&node__descriptor,
                                allocator, len, data);
}
void   node__free_unpacked
                     (Node *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   keep_alive__init
                     (KeepAlive         *message)
{
  static const KeepAlive init_value = KEEP_ALIVE__INIT;
  *message = init_value;
}
size_t keep_alive__get_packed_size
                     (const KeepAlive *message)
{
  assert(message->base.descriptor == &keep_alive__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t keep_alive__pack
                     (const KeepAlive *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &keep_alive__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t keep_alive__pack_to_buffer
                     (const KeepAlive *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &keep_alive__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
KeepAlive *
       keep_alive__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (KeepAlive *)
     protobuf_c_message_unpack (&keep_alive__descriptor,
                                allocator, len, data);
}
void   keep_alive__free_unpacked
                     (KeepAlive *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &keep_alive__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   choke__init
                     (Choke         *message)
{
  static const Choke init_value = CHOKE__INIT;
  *message = init_value;
}
size_t choke__get_packed_size
                     (const Choke *message)
{
  assert(message->base.descriptor == &choke__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t choke__pack
                     (const Choke *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &choke__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t choke__pack_to_buffer
                     (const Choke *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &choke__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Choke *
       choke__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Choke *)
     protobuf_c_message_unpack (&choke__descriptor,
                                allocator, len, data);
}
void   choke__free_unpacked
                     (Choke *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &choke__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unchoke__init
                     (Unchoke         *message)
{
  static const Unchoke init_value = UNCHOKE__INIT;
  *message = init_value;
}
size_t unchoke__get_packed_size
                     (const Unchoke *message)
{
  assert(message->base.descriptor == &unchoke__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unchoke__pack
                     (const Unchoke *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &unchoke__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unchoke__pack_to_buffer
                     (const Unchoke *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &unchoke__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Unchoke *
       unchoke__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Unchoke *)
     protobuf_c_message_unpack (&unchoke__descriptor,
                                allocator, len, data);
}
void   unchoke__free_unpacked
                     (Unchoke *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &unchoke__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   interested__init
                     (Interested         *message)
{
  static const Interested init_value = INTERESTED__INIT;
  *message = init_value;
}
size_t interested__get_packed_size
                     (const Interested *message)
{
  assert(message->base.descriptor == &interested__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t interested__pack
                     (const Interested *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &interested__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t interested__pack_to_buffer
                     (const Interested *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &interested__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Interested *
       interested__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Interested *)
     protobuf_c_message_unpack (&interested__descriptor,
                                allocator, len, data);
}
void   interested__free_unpacked
                     (Interested *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &interested__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   not_interested__init
                     (NotInterested         *message)
{
  static const NotInterested init_value = NOT_INTERESTED__INIT;
  *message = init_value;
}
size_t not_interested__get_packed_size
                     (const NotInterested *message)
{
  assert(message->base.descriptor == &not_interested__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t not_interested__pack
                     (const NotInterested *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &not_interested__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t not_interested__pack_to_buffer
                     (const NotInterested *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &not_interested__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NotInterested *
       not_interested__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NotInterested *)
     protobuf_c_message_unpack (&not_interested__descriptor,
                                allocator, len, data);
}
void   not_interested__free_unpacked
                     (NotInterested *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &not_interested__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   have__init
                     (Have         *message)
{
  static const Have init_value = HAVE__INIT;
  *message = init_value;
}
size_t have__get_packed_size
                     (const Have *message)
{
  assert(message->base.descriptor == &have__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t have__pack
                     (const Have *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &have__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t have__pack_to_buffer
                     (const Have *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &have__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Have *
       have__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Have *)
     protobuf_c_message_unpack (&have__descriptor,
                                allocator, len, data);
}
void   have__free_unpacked
                     (Have *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &have__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bitfield__init
                     (Bitfield         *message)
{
  static const Bitfield init_value = BITFIELD__INIT;
  *message = init_value;
}
size_t bitfield__get_packed_size
                     (const Bitfield *message)
{
  assert(message->base.descriptor == &bitfield__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bitfield__pack
                     (const Bitfield *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bitfield__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bitfield__pack_to_buffer
                     (const Bitfield *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bitfield__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Bitfield *
       bitfield__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Bitfield *)
     protobuf_c_message_unpack (&bitfield__descriptor,
                                allocator, len, data);
}
void   bitfield__free_unpacked
                     (Bitfield *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bitfield__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request__init
                     (Request         *message)
{
  static const Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   piece__init
                     (Piece         *message)
{
  static const Piece init_value = PIECE__INIT;
  *message = init_value;
}
size_t piece__get_packed_size
                     (const Piece *message)
{
  assert(message->base.descriptor == &piece__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t piece__pack
                     (const Piece *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &piece__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t piece__pack_to_buffer
                     (const Piece *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &piece__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Piece *
       piece__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Piece *)
     protobuf_c_message_unpack (&piece__descriptor,
                                allocator, len, data);
}
void   piece__free_unpacked
                     (Piece *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &piece__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cancel__init
                     (Cancel         *message)
{
  static const Cancel init_value = CANCEL__INIT;
  *message = init_value;
}
size_t cancel__get_packed_size
                     (const Cancel *message)
{
  assert(message->base.descriptor == &cancel__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cancel__pack
                     (const Cancel *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cancel__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cancel__pack_to_buffer
                     (const Cancel *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cancel__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cancel *
       cancel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cancel *)
     protobuf_c_message_unpack (&cancel__descriptor,
                                allocator, len, data);
}
void   cancel__free_unpacked
                     (Cancel *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cancel__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   port__init
                     (Port         *message)
{
  static const Port init_value = PORT__INIT;
  *message = init_value;
}
size_t port__get_packed_size
                     (const Port *message)
{
  assert(message->base.descriptor == &port__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t port__pack
                     (const Port *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &port__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t port__pack_to_buffer
                     (const Port *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &port__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Port *
       port__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Port *)
     protobuf_c_message_unpack (&port__descriptor,
                                allocator, len, data);
}
void   port__free_unpacked
                     (Port *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &port__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chord_message__init
                     (ChordMessage         *message)
{
  static const ChordMessage init_value = CHORD_MESSAGE__INIT;
  *message = init_value;
}
size_t chord_message__get_packed_size
                     (const ChordMessage *message)
{
  assert(message->base.descriptor == &chord_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chord_message__pack
                     (const ChordMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chord_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chord_message__pack_to_buffer
                     (const ChordMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chord_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChordMessage *
       chord_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChordMessage *)
     protobuf_c_message_unpack (&chord_message__descriptor,
                                allocator, len, data);
}
void   chord_message__free_unpacked
                     (ChordMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chord_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor node__field_descriptors[3] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(Node, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Node, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Node, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned node__field_indices_by_name[] = {
  1,   /* field[1] = address */
  0,   /* field[0] = key */
  2,   /* field[2] = port */
};
static const ProtobufCIntRange node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Node",
  "Node",
  "Node",
  "",
  sizeof(Node),
  3,
  node__field_descriptors,
  node__field_indices_by_name,
  1,  node__number_ranges,
  (ProtobufCMessageInit) node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor keep_alive__field_descriptors[1] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(KeepAlive, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned keep_alive__field_indices_by_name[] = {
  0,   /* field[0] = len */
};
static const ProtobufCIntRange keep_alive__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor keep_alive__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "KeepAlive",
  "KeepAlive",
  "KeepAlive",
  "",
  sizeof(KeepAlive),
  1,
  keep_alive__field_descriptors,
  keep_alive__field_indices_by_name,
  1,  keep_alive__number_ranges,
  (ProtobufCMessageInit) keep_alive__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor choke__field_descriptors[2] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Choke, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Choke, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned choke__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = len */
};
static const ProtobufCIntRange choke__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor choke__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Choke",
  "Choke",
  "Choke",
  "",
  sizeof(Choke),
  2,
  choke__field_descriptors,
  choke__field_indices_by_name,
  1,  choke__number_ranges,
  (ProtobufCMessageInit) choke__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor unchoke__field_descriptors[2] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Unchoke, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Unchoke, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unchoke__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = len */
};
static const ProtobufCIntRange unchoke__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor unchoke__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Unchoke",
  "Unchoke",
  "Unchoke",
  "",
  sizeof(Unchoke),
  2,
  unchoke__field_descriptors,
  unchoke__field_indices_by_name,
  1,  unchoke__number_ranges,
  (ProtobufCMessageInit) unchoke__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor interested__field_descriptors[2] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Interested, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Interested, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned interested__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = len */
};
static const ProtobufCIntRange interested__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor interested__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Interested",
  "Interested",
  "Interested",
  "",
  sizeof(Interested),
  2,
  interested__field_descriptors,
  interested__field_indices_by_name,
  1,  interested__number_ranges,
  (ProtobufCMessageInit) interested__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor not_interested__field_descriptors[2] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NotInterested, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NotInterested, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned not_interested__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = len */
};
static const ProtobufCIntRange not_interested__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor not_interested__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NotInterested",
  "NotInterested",
  "NotInterested",
  "",
  sizeof(NotInterested),
  2,
  not_interested__field_descriptors,
  not_interested__field_indices_by_name,
  1,  not_interested__number_ranges,
  (ProtobufCMessageInit) not_interested__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor have__field_descriptors[3] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Have, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Have, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pieceId",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Have, pieceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned have__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = len */
  2,   /* field[2] = pieceId */
};
static const ProtobufCIntRange have__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor have__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Have",
  "Have",
  "Have",
  "",
  sizeof(Have),
  3,
  have__field_descriptors,
  have__field_indices_by_name,
  1,  have__number_ranges,
  (ProtobufCMessageInit) have__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bitfield__field_descriptors[3] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bitfield, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bitfield, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bitfield",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bitfield, bitfield),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bitfield__field_indices_by_name[] = {
  2,   /* field[2] = bitfield */
  1,   /* field[1] = id */
  0,   /* field[0] = len */
};
static const ProtobufCIntRange bitfield__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor bitfield__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Bitfield",
  "Bitfield",
  "Bitfield",
  "",
  sizeof(Bitfield),
  3,
  bitfield__field_descriptors,
  bitfield__field_indices_by_name,
  1,  bitfield__number_ranges,
  (ProtobufCMessageInit) bitfield__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__field_descriptors[5] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Request, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Request, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Request, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "begin",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Request, begin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Request, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  3,   /* field[3] = begin */
  1,   /* field[1] = id */
  2,   /* field[2] = index */
  0,   /* field[0] = len */
  4,   /* field[4] = length */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  5,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor piece__field_descriptors[5] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Piece, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Piece, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Piece, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "begin",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Piece, begin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Piece, block),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned piece__field_indices_by_name[] = {
  3,   /* field[3] = begin */
  4,   /* field[4] = block */
  1,   /* field[1] = id */
  2,   /* field[2] = index */
  0,   /* field[0] = len */
};
static const ProtobufCIntRange piece__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor piece__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Piece",
  "Piece",
  "Piece",
  "",
  sizeof(Piece),
  5,
  piece__field_descriptors,
  piece__field_indices_by_name,
  1,  piece__number_ranges,
  (ProtobufCMessageInit) piece__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cancel__field_descriptors[5] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Cancel, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Cancel, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Cancel, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "begin",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Cancel, begin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Cancel, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cancel__field_indices_by_name[] = {
  3,   /* field[3] = begin */
  1,   /* field[1] = id */
  2,   /* field[2] = index */
  0,   /* field[0] = len */
  4,   /* field[4] = length */
};
static const ProtobufCIntRange cancel__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor cancel__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Cancel",
  "Cancel",
  "Cancel",
  "",
  sizeof(Cancel),
  5,
  cancel__field_descriptors,
  cancel__field_indices_by_name,
  1,  cancel__number_ranges,
  (ProtobufCMessageInit) cancel__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor port__field_descriptors[3] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Port, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Port, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "listenPort",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Port, listenport),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned port__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = len */
  2,   /* field[2] = listenPort */
};
static const ProtobufCIntRange port__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor port__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Port",
  "Port",
  "Port",
  "",
  sizeof(Port),
  3,
  port__field_descriptors,
  port__field_indices_by_name,
  1,  port__number_ranges,
  (ProtobufCMessageInit) port__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t chord_message__version__default_value = 417u;
static const ProtobufCFieldDescriptor chord_message__field_descriptors[12] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ChordMessage, version),
    NULL,
    &chord_message__version__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keep_alive",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, keep_alive),
    &keep_alive__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "choke",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, choke),
    &choke__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Unchoke",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, unchoke),
    &unchoke__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interested",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, interested),
    &interested__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "not_interested",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, not_interested),
    &not_interested__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "have",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, have),
    &have__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bitfield",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, bitfield),
    &bitfield__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, request),
    &request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "piece",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, piece),
    &piece__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cancel",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, cancel),
    &cancel__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChordMessage, msg_case),
    offsetof(ChordMessage, port),
    &port__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chord_message__field_indices_by_name[] = {
  3,   /* field[3] = Unchoke */
  7,   /* field[7] = bitfield */
  10,   /* field[10] = cancel */
  2,   /* field[2] = choke */
  6,   /* field[6] = have */
  4,   /* field[4] = interested */
  1,   /* field[1] = keep_alive */
  5,   /* field[5] = not_interested */
  9,   /* field[9] = piece */
  11,   /* field[11] = port */
  8,   /* field[8] = request */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange chord_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor chord_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ChordMessage",
  "ChordMessage",
  "ChordMessage",
  "",
  sizeof(ChordMessage),
  12,
  chord_message__field_descriptors,
  chord_message__field_indices_by_name,
  1,  chord_message__number_ranges,
  (ProtobufCMessageInit) chord_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
